# Generated by Django 3.2.9 on 2022-03-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Winery', models.CharField(max_length=500)),
                ('Location', models.CharField(max_length=500)),
                ('Image', models.URLField()),
                ('Color', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Light', models.FloatField()),
                ('Smooth', models.FloatField()),
                ('Dry', models.FloatField()),
                ('Soft', models.FloatField()),
                ('Gentle', models.FloatField()),
                ('Taste', models.TextField(null=True)),
                ('Food', models.TextField(null=True)),
                ('Grapes', models.TextField(null=True)),
                ('Alcohol', models.FloatField()),
            ],
        ),
    ]
