# Generated by Django 3.2.9 on 2022-03-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_userlikewine'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikewine',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
